version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_pipeline_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
      - AI_MODEL=huggingface
      - HF_API_KEY=hf_xxxxxxxxxxxxxxxx  # ton token HF
      - HF_MODEL_ID=facebook/bart-large-cnn 
    restart: always

  gradio-ui:
    build:
      context: .
      dockerfile: Dockerfile.gradio
    container_name: ai_pipeline_ui
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: always